name: Build and Release

on:
  push:
    branches:
      - master
      - main
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Windows
        run: bun run build:win && bunx electron-builder --win --publish always --config.compression=normal
        env:
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

  build-macos:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build macOS
        run: bun run build:mac && bunx electron-builder --mac --publish always --config.compression=normal
        env:
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
